### ISSUE TITLE
errors rise up when --no-eval is applied

### ISSUE THREAD

**Issue by liamsun2019** [ailingzengzzz/Split-and-Recombine-Net#2]
Dear author,

The following error rises up when --no-eval is applied during training:

Traceback (most recent call last):
  File "run.py", line 284, in <module>
    print_result(epoch, elapsed, lr, losses_3d_train, losses_3d_train_eval, losses_3d_valid)
  File "/mnt/hdd1/liam/Split-and-Recombine-Net/common/common_pytorch/experiment/tools.py", line 52, in print_result
    print(output)
UnboundLocalError: local variable 'output' referenced before assignment                                            

def print_result(epoch, elapsed, lr, losses_3d_train, losses_3d_train_eval, losses_3d_valid):
    if args.no_eval:
 output is not defined in case of no_eval.

**Comment by ailingzengzzz** [comment]
Sorry for the late reply. Because we always set --no-eval is False, we have not noticed this problem.
I have fixed it, since if --no-eval is True, there are no additional outputs named losses_3d_valid for line#284.
