### ISSUE TITLE
Code error!

### ISSUE THREAD

**Issue by Z-Z-J** [ailingzengzzz/Split-and-Recombine-Net#3]
In show_video.py and plot_pose2d.py,
![InkedQQ截图20211124162430_LI](https://user-images.githubusercontent.com/53818279/143201953-986dec46-80d0-4219-821f-bafce81e223b.jpg)
It should be [2,3], [0,4].

**Comment by ailingzengzzz** [comment]
Cool! Thanks for your kind reminder @Z-Z-J . I will fix it.
