### ISSUE TITLE
Why the size of data can up to 3 million and question about model_pos_train and model_pos

### ISSUE THREAD

**Issue by wyx1997** [ailingzengzzz/Split-and-Recombine-Net#6]
Hi, thanks for your great idea and your code.

I found that the log of single frame shows you have used over 3 million samples for training, but when I download the original .npz file, it only has 0.5 million samples. So I want to know how to generate those samples? What confuse me is that I use your TemporalModelOptimized1f model to train with only 0.5 million samples for over 50 epochs, but I can only get the same MPJPE as fc-baseline, so I don't know if I have missed sth or done sth wrong.

Secondly, I want to know the difference between model_pos_train and model_pos in run.py. As I see model_pos is only used for eval?

Waiting for your reply, very thanks.

**Comment by ailingzengzzz** [comment]
Hi @wyx1997, I'm sorry for the late reply.
1. The 3 million samples are double since we use a left-right flip as data augmentation by default. Where did you get the original .npz file?
2. model_pos is used to test, and model_pos_train is for training.
